//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ChungTu
    {
        public System.Guid Khoa { get; set; }
        public string SoChungTu { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string SoChungTu2 { get; set; }
        public Nullable<System.DateTime> Ngay2 { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<double> TongTien { get; set; }
        public string GhiChu { get; set; }
        public string MaCty { get; set; }
        public string MaDvi { get; set; }
        public string MaDvi2 { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public Nullable<int> UPDATED_BY { get; set; }
        public Nullable<System.DateTime> DELETE_DATE { get; set; }
        public Nullable<int> DELETE_BY { get; set; }
    }
}
