//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_TonKho
    {
        public System.Guid KHOA { get; set; }
        public Nullable<int> NAMKY { get; set; }
        public Nullable<int> NAM { get; set; }
        public Nullable<int> KY { get; set; }
        public string MaDvi { get; set; }
        public Nullable<int> Luong_Dau { get; set; }
        public Nullable<int> Luong_Nhap { get; set; }
        public Nullable<int> Luong_Xuat { get; set; }
        public Nullable<int> Luong_Cuoi { get; set; }
        public Nullable<double> THANHTIEN { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
    }
}
