//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supplement_Facts_products.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice_Sale
    {
        public string id_Invoice { get; set; }
        public System.DateTime dateOfSale { get; set; }
        public string id_Customer { get; set; }
        public double total { get; set; }
    }
}
