//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supplement_Facts_products.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice_Import
    {
        public string id_InvoiceImport { get; set; }
        public string id_vendor { get; set; }
        public System.DateTime dateofImport { get; set; }
        public Nullable<double> total { get; set; }
    }
}
