//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supplement_Facts_products.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string id_Product { get; set; }
        public string name_Product { get; set; }
        public double numberOf_Product { get; set; }
        public double importUnit_Price { get; set; }
        public double unitSelling_Price { get; set; }
        public string Image { get; set; }
        public string Note { get; set; }
    }
}
