//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supplement_Facts_products.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SFP_Conncetion : DbContext
    {
        public SFP_Conncetion()
            : base("name=SFP_Conncetion")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CUSTOMER> CUSTOMERs { get; set; }
        public virtual DbSet<DETAILS_IMPORT> DETAILS_IMPORT { get; set; }
        public virtual DbSet<INVOICE> INVOICEs { get; set; }
        public virtual DbSet<Invoice_Import> Invoice_Import { get; set; }
        public virtual DbSet<Invoice_Sale> Invoice_Sale { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<vendor> vendors { get; set; }
    }
}
