//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supplement_Facts_products.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vendor
    {
        public string id_vendor { get; set; }
        public string name_vendor { get; set; }
        public string address_vendor { get; set; }
        public string phone_vendor { get; set; }
    }
}
